/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StudyItem = IDL.Record({
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'notes' : IDL.Text,
});
export const ExerciseItem = IDL.Record({
  'reps' : IDL.Nat,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
});
export const Time = IDL.Int;
export const DayLog = IDL.Record({
  'id' : IDL.Nat,
  'studyItems' : IDL.Vec(StudyItem),
  'owner' : IDL.Principal,
  'exerciseItems' : IDL.Vec(ExerciseItem),
  'date' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DailyLog = IDL.Record({
  'completedStudyItems' : IDL.Nat,
  'totalExerciseItems' : IDL.Nat,
  'completedExerciseItems' : IDL.Nat,
  'totalStudyItems' : IDL.Nat,
});
export const DailyLogInput = IDL.Record({
  'studyItems' : IDL.Vec(StudyItem),
  'exerciseItems' : IDL.Vec(ExerciseItem),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllDayLogs' : IDL.Func([], [IDL.Vec(DayLog)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyLogsByCompletionStats' : IDL.Func(
      [],
      [IDL.Vec(DailyLog)],
      ['query'],
    ),
  'getDayLog' : IDL.Func([IDL.Nat], [DayLog], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDayLog' : IDL.Func([DailyLogInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StudyItem = IDL.Record({
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'notes' : IDL.Text,
  });
  const ExerciseItem = IDL.Record({
    'reps' : IDL.Nat,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
  });
  const Time = IDL.Int;
  const DayLog = IDL.Record({
    'id' : IDL.Nat,
    'studyItems' : IDL.Vec(StudyItem),
    'owner' : IDL.Principal,
    'exerciseItems' : IDL.Vec(ExerciseItem),
    'date' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DailyLog = IDL.Record({
    'completedStudyItems' : IDL.Nat,
    'totalExerciseItems' : IDL.Nat,
    'completedExerciseItems' : IDL.Nat,
    'totalStudyItems' : IDL.Nat,
  });
  const DailyLogInput = IDL.Record({
    'studyItems' : IDL.Vec(StudyItem),
    'exerciseItems' : IDL.Vec(ExerciseItem),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllDayLogs' : IDL.Func([], [IDL.Vec(DayLog)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyLogsByCompletionStats' : IDL.Func(
        [],
        [IDL.Vec(DailyLog)],
        ['query'],
      ),
    'getDayLog' : IDL.Func([IDL.Nat], [DayLog], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDayLog' : IDL.Func([DailyLogInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };