/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyLog {
  'completedStudyItems' : bigint,
  'totalExerciseItems' : bigint,
  'completedExerciseItems' : bigint,
  'totalStudyItems' : bigint,
}
export interface DailyLogInput {
  'studyItems' : Array<StudyItem>,
  'exerciseItems' : Array<ExerciseItem>,
}
export interface DayLog {
  'id' : bigint,
  'studyItems' : Array<StudyItem>,
  'owner' : Principal,
  'exerciseItems' : Array<ExerciseItem>,
  'date' : Time,
}
export interface ExerciseItem {
  'reps' : bigint,
  'completed' : boolean,
  'description' : string,
}
export interface StudyItem {
  'title' : string,
  'completed' : boolean,
  'notes' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllDayLogs' : ActorMethod<[], Array<DayLog>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyLogsByCompletionStats' : ActorMethod<[], Array<DailyLog>>,
  'getDayLog' : ActorMethod<[bigint], DayLog>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDayLog' : ActorMethod<[DailyLogInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];